### PR TITLE
v3 and v5 UUID support

### PR DESCRIPTION
**Pull request by OrangeDog**

### CODE REVIEW

**Comment by selfcontained** [comment]
It's a bummer this died here, a stand-alone uuid-v3 module would be super handy, but I'd hate to just rip this code off and call it my own.

**Comment by tracker1** [comment]
@selfcontained  @broofa  Could use/reference browerify's shim for node's crypto (incomplete, but iirc includes sha1 and md5 bits)

**Comment by coolaj86** [comment]
Any further thoughts on this?

I think it would be fine to put this in a subfolder such that you `require('node-uuid/v3')` or something like that.

**Comment by jamesdixon** [comment]
Bump. Any updates?

**Pull request closed without merging**
